version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/" # Lokasi composer.json
    schedule:
      interval: "weekly" # Bisa juga daily, monthly
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
